### ISSUE TITLE
Support cursors without goroutines

### ISSUE THREAD

**Issue by cmeon** [solher/arangolite#18]
Creating something like pagination seems expensive with this way.

Say I run a query like `FOR n IN nodes LIMIT 1000 RETURN 20`, by using `Run`, all 1000 results if found in the DB are returned, and no cursor key to manage the request.

Using `RunAsync` means having a goroutine `followCursor` created everytime there is more results in the cursor, and I am forced to get everything by checking if there is more just not to have hanging goroutine(s) in the background, or close the channel(meaning I have to begin going through the cursor again).

If I had multiple clients in an application running the same query, I have to keep these goroutines even though none of them might be interested in going through the list of results.

I propose we return the `result.ID` and let the user(developer) decide a proper method for getting the results.

**Comment by solher** [comment]
I get your point even if I'm not sure why one would like to read only the first page of the result he asked for.

The truth is I have to rewrite Arangolite. I wrote this package a long time ago and a lot of things feel dated/clumsy right now. I still like the core idea and the `Runnable` interface but I definitely have to rewrite a lot of the testing, ugly weird logging and api.

It would certainly keep the `Run` method because I have the feeling that a lot of users (me included) don't want to deal with pagination in 90% of the case. They just want to get their result and move on.
In the 10% remaining case, we should certainly not interfere and let the user decide, I totally agree.

BTW, I would be more than happy if you were interested in reviewing my PRs when the time comes.

**Comment by solher** [comment]
You can try the `v2.0.0` branch. It doesn't have goroutine magic anymore ;)

**Comment by cmeon** [comment]
Yeah! :D `v2.0.0` is really cool. More organized and all. Sorry I haven't had time to review some of the PRs lately.
